# anki
# Autogenerated from man page /usr/share/man/man1/anki.1.gz
complete -c anki -s b -d 'Use ~/. anki instead of ~/Anki as Anki\'s base folder'
complete -c anki -s p -d 'Load a specific profile'
complete -c anki -s l -d 'Start the program in a specific language (de=German, en=English, etc) SEE ALS…'

