# rpi-imager
# Autogenerated from man page /usr/share/man/man1/rpi-imager.1.gz
complete -c rpi-imager -l cli -d 'Do not launch the graphical interface; just flash the image given to the spec…'
complete -c rpi-imager -l debug -d 'Output extra debugging information on the console'
complete -c rpi-imager -l disable-telemetry -d 'Do not report OS writes to  http://rpi-imager-stats. raspberrypi. com/ '
complete -c rpi-imager -l disable-verify -d 'After writing the image, do not attempt to verify that the image was written …'
complete -c rpi-imager -l help -d 'Display a synopsis of the command line syntax and exit'
complete -c rpi-imager -l quiet -d 'Suppress all console output.  Only valid when run with R --cli '
complete -c rpi-imager -l qm -d 'Specify an alternate Qt message translations file to use with the GUI'
complete -c rpi-imager -l repo -d 'Instead of querying the Raspberry Pi servers for the list of available OS ima…'
complete -c rpi-imager -l sha256 -d 'Verify that the image matches the  expected-hash before writing it to the spe…'
complete -c rpi-imager -l version -d 'Report the version of the utility, and the default URI it will attempt to que…'

