# tab_spaces = 4
# hard_tabs = true
# reorder_impl_items = true
# imports_granularity = "Crate"
# normalize_comments = true
# group_imports = "StdExternalCrate"
# trailing_comma = "Never"
# trailing_semicolon = false
# use_field_init_shorthand = true
# use_try_shorthand = true
# unstable_features = true
# max_width = 160
# max_width = 999
# -------------------------

tab_spaces = 4
hard_tabs = true
max_width = 160
