# nvimpager
# Autogenerated from man page /usr/share/man/man1/nvimpager.1.gz
complete -c nvimpager -s a
complete -c nvimpager -s c
complete -c nvimpager -s h
complete -c nvimpager -s p
complete -c nvimpager -s v

